### PR TITLE
Add post about e-waste paper; Update daniel's profile

### PR DESCRIPTION
**Pull request by daniel-salmon**
## Summary

This branch adds a post about Chris and Daniel's recent publication on fraud and electronic waste. This includes adding a new image as well as adding a new file under `_posts/`.

In addition, the branch updates my profile with a more recent description and a link my website.

Thanks!
daniel

### CODE REVIEW

**Comment by daniel-salmon** [comment]
Hi @birdday I added the paper to the publications page as you requested. Let me know if there are any hiccups!

**Comment by birdday** [comment]
Typically need to add the post to the page as well (the posts system is a bit confusing) - I'll fix it this time around, but just an fyi for the future.

**Comment by daniel-salmon** [comment]
Hi, @birdday, sounds good. Could you enlighten me, though? Add what post to which page? Is this different than adding a new entry under `_posts` like that in f7f6140?

**Comment by birdday** [comment]
So you made mistakes which sort of cancelled out. You missed the publication header (line 8) for your own post, and instead made your publication a part of the previous publication. If you load the full file again, and scroll to the bottom, you will see that the publications also need to be added to a list, as identified by the line 8 equivalent. Since your post was nested within another post, it appeared, but not in the way we typically add them. Had you had the post header but not added the necessary line at the bottom of the file, it would just have not appeared. You can check out the changes I make when they are added later today.

**Pull request merged**
