### PR TITLE
professional head shot

### PR DESCRIPTION
**Pull request by paulboone**
Added a professional head shot of me. Of course it breaks the design, but I thought I'd let the admin suggest a fix or reject the PR request... ;)

### CODE REVIEW

**Comment by kbsezginel** [comment]
paulprofilepic

I tried to remove the background but it's a bit tricky since it's not solid color. I like the new picture better but I think we should stick with the white background for all images. What do you think of this one?

**Comment by kbsezginel** [comment]
paulprofilepic2

Here is an alternative one with softness to mask cropping imperfections. We need a photo manipulation expert here.

**Comment by kbsezginel** [comment]
paulprofilepic3

Alright, last one with softness no filters.

**Comment by paulboone** [comment]
Last one is by far the best. I tried to use an online background remover and it was TERRIBLE, these are much better.

**Comment by kbsezginel** [comment]
Yeah those generally don't work well :) I also like this last one so feel free to add it whenever.

**Comment by paulboone** [comment]
PR updated with new image. Think you can merge this now!

**Pull request merged**
